name: toolchain

on: 
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt-get update && sudo apt-get install -y unzip libtool-bin ccache curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio bc zip git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin liblzma-dev
      - name: Start Build
        run: |
          make toolchain/build
          cd toolchain-mipsel/toolchain-4.4.x
          tar cJf ../mipsel-linux-uclibc-gcc10.tar.xz *
      - uses: actions/upload-artifact@main
        with:
          name: toolchain
          path: toolchain-mipsel/mipsel-linux-uclibc-gcc10.tar.xz
      - uses: svenstaro/upload-release-action@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: toolchain-mipsel/mipsel-linux-uclibc-gcc10.tar.xz
          tag: toolchain
          overwrite: true
